version: '3.3'
services:
  db:
    image: mysql:8.0
    # command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
 
    volumes:
      - my-db:/var/lib/mysql
 
volumes:
  my-db: